### PR TITLE
Fix compiler warnings

### LINKED ISSUE #373: Compiler warnings
```
core/src/InfiniteDimensionalMCMCSampler.C: In member function 'void QUESO::InfiniteDimensionalMCMCSampler::_append_scalar_dataset(hid_t, double)':
core/src/InfiniteDimensionalMCMCSampler.C:279:9: warning: variable 'err' set but not used [-Wunused-but-set-variable]
core/src/InfiniteDimensionalMCMCSampler.C: In member function 'hid_t QUESO::InfiniteDimensionalMCMCSampler::_create_scalar_dataset(const string&)':
core/src/InfiniteDimensionalMCMCSampler.C:271:9: warning: 'dummy' may be used uninitialized in this function [-Wmaybe-uninitialized]
```

```
In file included from /opt/apps/ossw/libraries/boost/boost-1.51.0/sl6/gcc-4.7/include/boost/random/detail/large_arithmetic.hpp:19:0,
                 from /opt/apps/ossw/libraries/boost/boost-1.51.0/sl6/gcc-4.7/include/boost/random/detail/const_mod.hpp:23,
                 from /opt/apps/ossw/libraries/boost/boost-1.51.0/sl6/gcc-4.7/include/boost/random/linear_congruential.hpp:30,
                 from /opt/apps/ossw/libraries/boost/boost-1.51.0/sl6/gcc-4.7/include/boost/random/additive_combine.hpp:27,
                 from /opt/apps/ossw/libraries/boost/boost-1.51.0/sl6/gcc-4.7/include/boost/random.hpp:36,
                 from ../inc/queso/RngBoost.h:29,
                 from core/src/Environment.C:29:
/opt/apps/ossw/libraries/boost/boost-1.51.0/sl6/gcc-4.7/include/boost/random/detail/integer_log2.hpp:71:35: warning: always_inline function might not be inlinable [-Wattributes]
```

```
stats/src/TKGroup.C: In instantiation of 'QUESO::BaseTKGroup<V, M>::BaseTKGroup() [with V = QUESO::GslVector; M = QUESO::GslMatrix]':
stats/src/TKGroup.C:132:23:   required from here
stats/src/TKGroup.C:41:28: warning: passing NULL to non-pointer argument 1 of 'std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type, const value_type&, const allocator_type&) [with _Tp = const QUESO::GslVector*; _Alloc = 
std::allocator<const QUESO::GslVector*>; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = const QUESO::GslVector*; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<const QUESO::GslV
ector*>]' [-Wconversion-null]
```

```
surrogates/src/InterpolationSurrogateBuilder.C: In instantiation of 'void QUESO::InterpolationSurrogateBuilder<V, M>::partition_work() [with V = QUESO::GslVector; M = QUESO::GslMatrix]':
surrogates/src/InterpolationSurrogateBuilder.C:233:23:   required from here
surrogates/src/InterpolationSurrogateBuilder.C:101:5: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```

```
surrogates/src/InterpolationSurrogateIOASCII.C: In instantiation of 'void QUESO::InterpolationSurrogateIOASCII<V, M>::read(const string&, const QUESO::FullEnvironment&, const string&) [with V = QUESO::GslVector; M = QUESO::GslMatrix; std
::string = std::basic_string<char>]':
surrogates/src/InterpolationSurrogateIOASCII.C:252:23:   required from here
surrogates/src/InterpolationSurrogateIOASCII.C:60:5: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
surrogates/src/InterpolationSurrogateIOASCII.C:85:5: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
surrogates/src/InterpolationSurrogateIOASCII.C:109:5: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
surrogates/src/InterpolationSurrogateIOASCII.C:155:5: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```

There are probably others, but this is what I found while trying to implement something.

### PR DESCRIPTION
**Pull request by dmcdougall**
Fixes #373.

### CODE REVIEW

File: src/surrogates/src/InterpolationSurrogateIOASCII.C [hunk 1]
```diff
@@ -59,7 +59,7 @@ namespace QUESO
 
     // Only processor 0 does the reading.
     // We'll broadcast the data as needed
-    if( env.fullRank() == root )
+    if( env.fullRank() == (int)root )
```
Comment (dmcdougall) [inline src/surrogates/src/InterpolationSurrogateIOASCII.C]: @roystgnr I'd like to know what you think about changes like this.  Another option is to have our `MpiComm` and `BaseEnvironment` store an `unsigned int` member variable instead, so that casts like this aren't needed.

Comment (roystgnr) [inline src/surrogates/src/InterpolationSurrogateIOASCII.C]: Why don't we declare root to be an int here?

Comment (roystgnr) [inline src/surrogates/src/InterpolationSurrogateIOASCII.C]: In libMesh we have a proc_id_type, but since we're only supporting MPI for distributed parallelism everything ends up cast to int in the end; we just let users save a few megabytes if they want to limit themselves to 65K cores.

File: src/surrogates/src/InterpolationSurrogateIOASCII.C [hunk 2]
```diff
@@ -49,7 +49,7 @@ namespace QUESO
                                                  int reading_rank )
   {
     // Root processor
-    unsigned int root = reading_rank;
+    int root = reading_rank;
```
Comment (dmcdougall) [inline src/surrogates/src/InterpolationSurrogateIOASCII.C]: @roystgnr Better?

Comment (roystgnr) [inline src/surrogates/src/InterpolationSurrogateIOASCII.C]: Yup.  That should hold us for a decade or more; at least until we need to make the MPI-5 upgrade to handle 2.2 billion rank machines.

Comment (csim314) [inline src/surrogates/src/InterpolationSurrogateIOASCII.C]: "to handle 2.2 billion rank machines.�

That�ll happen in a few months at the rate China is leveling up. :)
